### ISSUE TITLE
Missing font options

### ISSUE THREAD

**Issue by TakingItCasual** [Gnurou/tagainijisho#155]
There are places where kana/kanji are used that don't have an option to use a font other than the default one, such as printing, stroke order boxes, and reading practice. This is especially frustrating when a default font without support (or with poor support) for japanese characters is preferred.

**Comment by Gnurou** [comment]
Hopefully I have a radical fix for this issue: from now on, Tagaini will include the Noto font and will use it to display anything Japanese. This ensures all users have a consistent experience, and an actual Japanese font since some kanji are displayed differently if only Chinese fonts are available.

So as a result, fonts options actually decrease, and from the next release on only the size can be adjusted. Romaji will be drawn using the user's default font, and Japanese using Noto.
