### ISSUE TITLE
Search bar automatically capitalizes first word; changes the whole search results

### ISSUE THREAD

**Issue by utsubushi621** [Gnurou/tagainijisho#157]
I tried searching for a word by using Romaji. My example was typing "Ame" with a capital A. This only gave me 2 Results under the "All" Category. When I typed it in all lower case (ame), I finally got what I wanted which were all the words that are spelled containing ame. When I click any of the objects in the search results, the search bar automatically corrects or capitalizes the word from "ame" to "Ame," taking me back to the problem that only 2 objects are shown in the search results. This is a problem because I can't even scroll down through the list for the search results for "ame" which there are many. I can't see them because of this problem, since clicking outside of the search bar immediately "corrects" the search keyword by capitalizing. I love the program so far, I love it so much I really want to study Japanese and this program is just what I need to ease that, so if this problem would get resolved I would very much appreciate it, I think it shouldn't be too hard even though I'm not a programmer I hope it isn't hard to fix. Thanks

**Comment by firatakandere** [comment]
I think the "real" problem is that the searches are case-sensitive, I think case-insensitive searching would be better.

**Comment by Gnurou** [comment]
Right, all search terms should be uncapitalized before being searched.

I still do not understand that part of the initial post though:

*"When I click any of the objects in the search results, the search bar automatically corrects or capitalizes the word from "ame" to "Ame,"*

I don't see how this can happen, unless something is missing in the description. Barely clicking on a search result should have no influence at all on the content of the search bar.

**Comment by firatakandere** [comment]
I "sometimes" have the same autocorrect issue, I have just realized it and I'm still trying to figure it out why.

I think uncapitaling the search terms would not work well since there are capital letters in the database entries.

Adding `collate nocase` to the select query may help, or better you may want to specify `collate nocase` in the column definition which takes the lowercase versions of values when a comparison is performed. Second option is said to be working faster.

http://www.sqlite.org/datatype3.html#collation

**Comment by Gnurou** [comment]
Looking for an English word and looking for a romanized word (what the initial poster tries to do) are actually two different things.

In the first case, SQLite's FTS engine is used, which is case-insensitive, so the result is as expected.

In the second case, the romaji string is translated in katakana, and the search is performed on that string. The bug is that capital letters are not considered for romaji translation, so in the exemple given the search corresponds to the litteral "ame" (and not アメ). The fact that in that precise exemple the returned results all have "Ame" written with a capital just adds to the confusion, but other exemples support my point (try "Mata" and "mata" for instance).

So the fix should simply be to convert a ronaji string to lower-case before trying to translate it to kana. As the initial poster mentioned, this is quite trivial.

I don't really know about the autocorrect thing though, for I have never met it. Details on the system used might help here.

**Comment by utsubushi621** [comment]
I think I figured out the problem. I restarted the program and typed in ame in all lower case once again, then I was able to click the search result objects with no problem and the autocapitalizaion issue stopped. So then I wanted to know why this happened, when I typed in Ame again in the search box with capitalized A I got the problem again therefore maybe the problem originally happened if I accidentally searched for Ame with an uppercase A. So it seems everything should be fine as long as you search in only lower case. I kept experimenting to see if there was a workaround, just in case I didn't want to have to restart the program everytime. I just searched again lower case ame with a space after ame ("ame ") and this also resolved the issue. If I could make a video of how clicking a search result object -or even using the mousewheel to scroll down through the results or clicking anything in the program changed the search text from lower to uppercase- I would but it might not be necessary now that the problem is solved and there is a work-around. If any developer out there is interested though I'll do it. Thanks for the help everyone

**Comment by Gnurou** [comment]
6 years to do a case-insensitive search, how fast is that. :)

The long-standing issue that prevented me to make a release seems to finally be fixed, so the fix will be available in 1.2 to be released as soon as I remember the process to make a release.
