### ISSUE TITLE
Qt5-based release

### ISSUE THREAD

**Issue by a17r** [Gnurou/tagainijisho#215]
Qt4 support has ended in 2015, and Gentoo and Debian (Buster) are not the only distributions busy with removing Qt4 depending packages right now.

Is there a schedule or a list of known bugs to be fixed for a new release with Qt5 support?

**Comment by Gnurou** [comment]
Hi, sorry for the delayed answer.

There is a plan for Qt5 migration. Kind of. Actually master already works on Qt5 and takes care of migrating the data from the older Qt4 versions. There are still bugs that I need to fix before making the release though (see https://github.com/Gnurou/tagainijisho/milestone/6). The most important ones are already being worked on. Hopefully I can complete that in a reasonable time.

**Comment by XVilka** [comment]
Gentoo masked the program for removal. Hopefully they will accept ebuild back once Qt5 migration is finished.

**Comment by a17r** [comment]
That's not quite correct, only Qt4-depending version is masked.
```
$ eshowkw tagainijisho
Keywords for app-i18n/tagainijisho:
                           |                           a     |       |  
                           |                           m     |       |  
                           |                           d   x |       |  
                           |                           6   8 |       |  
                           |                           4   6 |   u   |  
                           | a a   a     p           s |   | |   n   |  
                           | l m   r i   p   h m s   p f m f | e u s | r
                           | p d a m a p c x p 6 3   a b i b | a s l | e
                           | h 6 r 6 6 p 6 8 p 8 9 s r s p s | p e o | p
                           | a 4 m 4 4 c 4 6 a k 0 h c d s d | i d t | o
---------------------------+---------------------------------+-------+-------
               [M]1.0.3-r1 | o ~ o o o o o ~ o o o o o o o o | 5 # 0 | gentoo
1.2.0_pre20180610092832    | o ~ o o o o o ~ o o o o o o o o | 6 o   | gentoo
                   9999    | o o o o o o o o o o o o o o o o | 6 o   | gentoo
```

**Comment by eshimischi** [comment]
Qt4 itself looks so ugly on laptops with Retina Display as well, so really hope to get Qt5 based version. Thanks! Arigatou gozaimasu

**Comment by onitake** [comment]
Sadly, the package was now removed from Debian unstable/testing, in part because Qt4 has been deprecated, but also because of a lack of maintainers: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939281

It would be great if the package could be reintroduced, but a released Qt5 version would be a requirement for this. Thank you for your consideration.

**Comment by prometheus42** [comment]
Because of the removal from Debian the package can no longer be installed in Ubuntu 19.10 (Eoan Ermine) using the official package repository.

Building a DEB package from sources works fine, although after the installation, the following error message is given: "Fatal: kanjidic2 plugin fatal error: cannot find main database file!". Copying all dictionaries from /usr/share/tagainijisho to ~/.local/share/Tagaini Jisho fixes this issue.

Tagaini Jisho is a really good offline dictionary. But it would be much more convenient and accessible to be able to install it directly from the repositories. So thank you for this great program! And if I can help you, please let me know.

**Comment by onitake** [comment]
It doesn't look like the Debian package is built with any special path options: https://salsa.debian.org/debian/tagainijisho/blob/master/debian/rules *

Have you checked which paths are consulted by Tagaini for the kanjidic?

* I'm also sure this rules files could be _greatly_ simplified in this day and age.

**Comment by hosiet** [comment]
If a new stable release of tagainijisho is tagged with complete Qt5 support, please let me know. I can reintroduce it into Debian main repository (and thus Ubuntu). Before that, I can't do anything meaningful if the most recent release was stuck back in 2015.

**Comment by Staudey** [comment]
To add one data point to this issue:
This is also one of the blockers for the depreciation of Qt4 in Solus https://dev.getsol.us/T6074

It has already been [semi-officially announced](https://dev.getsol.us/T6074#172969) that tagainijisho might be removed from the repository. Though as there has been a lot of progress in that regard here lately, that statement isn't quite up to date. Definitely would be preferable if a Qt5 build were possible when the time for another consideration arrives. (e.g. in the case of hydrogen-music a Qt5-capable RC was sufficient, so it doesn't have to be a full release either)

**Comment by Azarilh** [comment]
Can't we just get an AppImage which doesn't require the app to be qt5? ( i guess!?!? )

**Comment by onitake** [comment]
> Can't we just get an AppImage which doesn't require the app to be qt5? ( i guess!?!? )

If you're happy to continuously maintain all dependencies in the custom AppImage and port security patches back from Qt5 to Qt4...
Qt4 has been out of support since 2015: https://en.wikipedia.org/wiki/Qt_version_history#Qt_4

**Comment by Gnurou** [comment]
I think I should apologize about the current situation. The latest git code has been building and running quite well with Qt5 for some time already, but I am refraining from making a release due to some still in-progress features (nothing too blocking though) and, more importantly, a more critical issue regarding the JMdict data.

JMdict data is constantly evolving, and this can result in some entries being merged or simply removed. Tagaini is typically pretty bad at handling this, and although I have tried to do some tracking in order to detect merges and transparently replace references to obsolete entries with the new ones, in some cases this could have resulted into entries simply disappearing from users' study list.

This phenomenon is now amplified by the fact the next release will introduce 5 years worth of JMdict updates and entries removal. I really don't want users to lose data that has been carefully crafted over the years. I have been trying to find a solution to handle this gracefully with the JMdict community, but it is not easy to solve from their end either.

So in the end I have decided to keep deleted entries as they are in the user database, and display along with them a big warning that they should be re-looked up and replaced (probably with a UI to help with this). This also requires to maintain a new database of all deleted JMdict entries so the user knows what the entry was about originally. It took me quite some time to think about this solution (and to devise a plan to extract said deleted entries), and I plan to implement it soon and finally do a new release.

Of course this is still playing catch-up with the times. Tagaini's UI is by all means obsolete and unadapted to how most people are studying today, but that's a different story. All that to say that I hope to do an actual Qt5 release sometime during the next few months, depending on my availability (and motivation) to work on this.

**Comment by Staudey** [comment]
@Gnurou There is absolutely no need to apologize! You're doing great work, and as you've made clear there are a lot of hurdles in your way. For my part I didn't want to pressure you, just detail the situation in the Solus repository; also as a way for me to subscribe to the discussion. I think the others had similar motivations.

**Comment by Gnurou** [comment]
It took a super long time, but the issues I had with deleted JMdict entries are finally solved (or rather, worked around) and release 1.1.90 is the first (beta) release to feature Qt5! Closing this issue, thanks everyone for your patience.

**Comment by onitake** [comment]
Many thanks for the effort!
I'll try to find a DD willing to support a reintroduction into Debian. Fingers crossed!

**Comment by Gnurou** [comment]
Thanks! That would be great, although after the hiatus the software took I would understand if it took some time before distros package it again.
