### ISSUE TITLE
SKIP codes on non-debian platforms

### ISSUE THREAD

**Issue by sopoforic** [Gnurou/tagainijisho#225]
I see in 9edd248 you removed support for SKIP codes (due to [this debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741221)).

If my reading of [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=182652) is correct, debian is already including a version of kanjidic2 with the SKIP codes removed, so unless Tagaini Jisho is distributing a second copy of the dictionary on debian (maybe this is the case), I don't understand the problem.

In a broader sense, I don't think SKIP codes are eligible for copyright and any patents would already have expired, and even if there were such encumbrances the data in the kanjidic2 is distributed with permission, so supporting that in Tagaini Jisho would not be taking advantage of any illicit distribution.

Would you consider returning support for SKIP codes, at least for non-debian platforms?

**Comment by bhbuehler** [comment]
Is this not an issue that has already been resolved? I sympathize because I too am using a distribution which does not have the latest version, but the releases section shows "SKIP code support has also been re-enabled" in the latest version (released 2015-03-08). Clearly the repositories need to be updated, but I'm not sure this is an issue with the software.

**Comment by sopoforic** [comment]
You are correct. I'm not sure how I failed to notice that the latest version has had support re-enabled, but this is a mistake on my part, and this bug can certainly be closed.
