### ISSUE TITLE
Arabic Dictionary

### ISSUE THREAD

**Issue by objestik** [Gnurou/tagainijisho#227]
I want to add Arabic dictionary to the program, How can I do that?

**Comment by Gnurou** [comment]
Hi,

Do you mean a Japanese to Arabic dictionary?

The dictionary data comes from the JMdict and Kanjidic2 projects, so that's where it should be added. This is a gigantic task though.

A while ago I have started an effort to make translating both projects easier, but have run out of time to maintain it properly though. However this could be a starting point:

https://www.tagaini.net/jmdict-i18n/

**Comment by objestik** [comment]
I already have a Japanese to Arabic dictionary files in SQLite. It's from this http://www.ogurano.net.
